name: "Run Custom Actions"
on:
  # Used for manually triggering jobs
  workflow_dispatch:
  # Run on changes
  push:

jobs:
  custom-actions-job:
    runs-on: ubuntu-latest
    name: Run Custom Actions
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Custom Composite Action
      uses: ./sh
    - name: Custom JavaScript Action
      uses: ./javascript